server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: ${GATEWAY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email,roles
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/comic-inventory

  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: library
          uri: lb://LIBRARY-SERVICE
          predicates: [ Path=/library/** ]
          filters:   [ StripPrefix=1 ]
        - id: stock
          uri: lb://STOCK-SERVICE
          predicates: [ Path=/stock/** ]
          filters:   [ StripPrefix=1 ]
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,gateway
  endpoint:
    health:
      show-details: never